### ISSUE TITLE
When loading a file (with existing project designation) the project is not set

### ISSUE THREAD

**Issue by willismonroe** [PEKennedy/ATF_Editor#1]
When I load an existing ATF file with a pre-set project definition, the project dropdown doesn't set to the file's project.

**Comment by PEKennedy** [comment]
Fixed with [c960892](https://github.com/PEKennedy/ATF_Editor/commit/c96089252e889c1a162b1b710bcde8c5573ec421)

**Comment by willismonroe** [comment]
Amazing, thanks Peter!
